server.port=8080

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/subsidydb?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${USER_NAME:root}
spring.datasource.password=${USER_PASSWORD}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Cloudinary
# ===============================
cloudinary.cloud-name=e2fxcdp3
cloudinary.api-key=216275359857256
cloudinary.api-secret=PDKprn2_MpX25UjEVJeFd_ljY64

# ===============================
# File Upload Limits
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# JWT
# ===============================
app.jwt.secret=9a2f8c4e1b7d5e3a8f0c2b6d4e1a9f3b7e5c1d8a2f4b6e9c3d7a1f5b8e2c4d6
app.jwt.expiration-ms=86400000